name: Deploy To EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle 실행 권한 부여
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build -x test

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/libs/*.jar
          target: /home/ubuntu/

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo pkill -f UniScope || true
            sudo fuser -k -n tcp 8080 || true
            sleep 3
            
            cd /home/ubuntu
            rm -f nohup.out
                        
            nohup java -jar \
              -Xms256m -Xmx512m \
              -XX:+UseG1GC \
              -Dspring.profiles.active=prod \
              -DDB_HOST=localhost \
              -DDB_USERNAME=${{ secrets.DB_USERNAME }} \
              -DDB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              -DJWT_SECRET=${{ secrets.JWT_SECRET }} \
              build/libs/UniScope-0.0.1-SNAPSHOT.jar &
